## To-do
### words to compare DONE
### num of boxes DONE
### populate top boxes with 0's DONE
### add nums | side | down | accros | 0 DONE
### select what arrow / number to put in box DONE
### track back (need to find the largest to start the track back)
### print alignment (need to enter the right gaps)
### match = 5 | mismatch = -1 | gap -4
### Problem?: The dictionary that saves the actions that are applyed to a cell doesnt account for when 0 goes to a cell
### Problem: if there is a cell that as 2 or more arrows that point to the cell I need to figure out the the math going from both cells [maybe if going though the cell action list count the # of times the TO cell shows up mark where in the list it was found and make a copy of the list to do math in a seperate loop]

In [2]:
import numpy as np

### # of boxes = top word + 1 * side word + 1

In [14]:
#top_words = input("Enter top word: ")
#side_words = input("Enter side word:")
top_words = 'toe'
side_words = 'steps'
# create the 2D numpy array
arr = np.zeros(((len(side_words) + 1), (len(top_words) + 1)))

    
print(arr)
print(arr.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(6, 4)


In [15]:

top_word = []
side_word = []
for x in top_words:
    top_word.append(x)
print(top_word)

for x in side_words:
    side_word.append(x)
print(side_word)

['t', 'o', 'e']
['s', 't', 'e', 'p', 's']


In [16]:
dic = {}

In [17]:

#function that adds 5 to the cell if there is a match
def match(row, col, pas):
    arr[row,col] = arr[row-1,col-1] + 5
    largest = arr[row,col] 
    dic.update({pas: ((row-1,col-1),(row,col), 'diagnal')})
    print(dic)

#function that does the math for mismatchs and gap penaltys. adds the result to a dictionary where all the actions are stored
def math(row,col, pas):
    largest = 0
    
    #mismatch diagnal arrow
    mcomp = arr[row-1,col-1]
    mis = mcomp - 1

    #gap down arrow
    dcomp = arr[row-1,col]
    down = dcomp - 4
    
    #gap across arrow
    acomp = arr[row,col-1]
    across = acomp - 4

    #find which of the 3 is the largest
    #Dic (passthough #: from cell, to cell, arrow
    if mis > down and mis > across and mis > 0:
        largest = mis
        dic.update({pas: ((row-1,col-1),(row,col),'diagnal')})
        print(dic)
    if down > mis and down >= across and down > 0:
        largest = down
        dic.update({pas: ((row-1,col),(row,col), 'down')})
        print(dic)
    if across > mis and across >= down and across> 0:
        largest = across
        dic.update({pas: ((row,col-1),(row,col), 'across')})
        print(dic)

    #check to see if the largest number is larger than 0 if it is less than zero it is applyed to the cell
    if largest > 0:
        arr[row,col] = arr[row,col] + largest
    if largest <= 0:
        arr[row,col] = arr[row,col] + 0
        dic.update({pas: ((row,col), 'Zero')})
    
  
pas = 0
row = 0
col = 0

#x is itterating through each row
for x in arr:
    #The if skips the first row because we dont need to change anything in it 
    
    if row != 0 and row <= len(side_word):
        #y goes through each number in the row 
        for y in x:
            if col != 0 and col <= len(top_word):
                if side_word[row-1] == top_word[col-1]:
                # send this to the match
                    match(row,col,pas)
                    pas += 1
                else:
                    math(row,col,pas)
                    pas += 1
                #send to the math for Gap and Mis
            col += 1
                
    col = 0
    row += 1
   
print(arr) 

{0: ((1, 1), 'Zero'), 1: ((1, 2), 'Zero'), 2: ((1, 3), 'Zero'), 3: ((1, 0), (2, 1), 'diagnal')}
{0: ((1, 1), 'Zero'), 1: ((1, 2), 'Zero'), 2: ((1, 3), 'Zero'), 3: ((1, 0), (2, 1), 'diagnal'), 4: ((2, 1), (2, 2), 'across')}
{0: ((1, 1), 'Zero'), 1: ((1, 2), 'Zero'), 2: ((1, 3), 'Zero'), 3: ((1, 0), (2, 1), 'diagnal'), 4: ((2, 1), (2, 2), 'across'), 5: ((2, 3), 'Zero'), 6: ((2, 1), (3, 1), 'down')}
{0: ((1, 1), 'Zero'), 1: ((1, 2), 'Zero'), 2: ((1, 3), 'Zero'), 3: ((1, 0), (2, 1), 'diagnal'), 4: ((2, 1), (2, 2), 'across'), 5: ((2, 3), 'Zero'), 6: ((2, 1), (3, 1), 'down'), 7: ((2, 1), (3, 2), 'diagnal')}
{0: ((1, 1), 'Zero'), 1: ((1, 2), 'Zero'), 2: ((1, 3), 'Zero'), 3: ((1, 0), (2, 1), 'diagnal'), 4: ((2, 1), (2, 2), 'across'), 5: ((2, 3), 'Zero'), 6: ((2, 1), (3, 1), 'down'), 7: ((2, 1), (3, 2), 'diagnal'), 8: ((2, 2), (3, 3), 'diagnal')}
{0: ((1, 1), 'Zero'), 1: ((1, 2), 'Zero'), 2: ((1, 3), 'Zero'), 3: ((1, 0), (2, 1), 'diagnal'), 4: ((2, 1), (2, 2), 'across'), 5: ((2, 3), 'Zero'), 6:

In [18]:
#dictionalry (From cell)(to cell)(action / arrow of the cell leading from ---> to)
for x in dic: 
    print(dic[x])

((1, 1), 'Zero')
((1, 2), 'Zero')
((1, 3), 'Zero')
((1, 0), (2, 1), 'diagnal')
((2, 1), (2, 2), 'across')
((2, 3), 'Zero')
((2, 1), (3, 1), 'down')
((2, 1), (3, 2), 'diagnal')
((2, 2), (3, 3), 'diagnal')
((4, 1), 'Zero')
((4, 2), 'Zero')
((3, 2), (4, 3), 'diagnal')
((5, 1), 'Zero')
((5, 2), 'Zero')
((5, 3), 'Zero')


In [19]:
#meathod used to find the largest number in the table
print('The largest number in the table is:' , arr.max())
#meathod used to find the index in the table of the largest number 
i, j = np.unravel_index(arr.argmax(), arr.shape)
print(i,j)

The largest number in the table is: 6.0
3 3


In [22]:
gap_print = []
lar = (i,j)

keys = list(dic.keys())
val = list(dic.values())
found = False
x = 0


#while loop to find the largest cell 
#need to change to when it is not done (when the search thing gets to a from cell that is zero then stop)
while found == False:
    temp = val[-x]
    #first of statement to find the largest if the first ellement in the cell entry is the same address as the largest number than
    if temp[1] == lar:
        print('large found')
        #adds the arrow direction to a list to be printed later
        gap_print.append(temp[2])
        fro = 
        #for loop to find anything that is attached to the 
    x +=1

    

SyntaxError: invalid syntax (1188480316.py, line 19)