## To-do
### words to compare DONE
### num of boxes DONE
### populate top boxes with 0's DONE
### add nums | side | down | accros | 0 DONE
### select what arrow / number to put in box DONE
### track back (need to find the largest to start the track back) DONE?
### print alignment (need to enter the right gaps) DONE
### match = 5 | mismatch = -1 | gap -4
### Problem: if there is a cell that as 2 or more arrows that point to the cell I need to figure out the the math going from both cells [maybe if going though the cell action list count the # of times the TO cell shows up mark where in the list it was found and make a copy of the list to do math in a seperate loop]

In [1]:
import numpy as np

### # of boxes = top word + 1 * side word + 1

In [118]:
top_words = input("Enter top word: ")
side_words = input("Enter side word:")
#control words so I don't have to input the words every time
#top_words = 'salty'
#side_words = 'plate'

# create a 2D numpy array that is the legth of the 2 words
arr = np.zeros(((len(side_words) + 1), (len(top_words) + 1)))

    
print(arr)
print(arr.shape)

Enter top word:  salty
Enter side word: plate


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
(6, 6)


In [119]:
#The following loops convert the words entered last cell into a list. This will make it easy to insert gaps for the local alignment
top_word = []
side_word = []
for x in top_words:
    top_word.append(x)
print(top_word)

for x in side_words:
    side_word.append(x)
print(side_word)

['s', 'a', 'l', 't', 'y']
['p', 'l', 'a', 't', 'e']


In [120]:
#This dictinary is used to hold the values of [which cell the math was done from | what cell the result is going to | which arrow the result is]
dic = {}

In [121]:
pas = 0
row = 0
col = 0
#function that adds 5 to the cell if there is a match
def match(row, col, pas):
    
    arr[row,col] = arr[row-1,col-1] + 5
    largest = arr[row,col] 
    dic.update({pas: ((row-1,col-1),(row,col), 'diagnal')})
    
    

#function that does the math for mismatchs and gap penaltys. adds the result to the dictionary where all the actions are stored
def math(row,col, pas):
    largest = 0
    
    #mismatch diagnal arrow
    mcomp = arr[row-1,col-1]
    mis = mcomp - 1

    #gap down arrow
    dcomp = arr[row-1,col]
    down = dcomp - 4
    
    #gap across arrow
    acomp = arr[row,col-1]
    across = acomp - 4

    #find which of the 3 is the largest
    #Dic (passthough #: from cell, to cell, arrow)
    
    if mis > down and mis > across and mis > 0:
        largest = mis
        dic.update({pas: ((row-1,col-1),(row,col),'diagnal')})
        
    if down > mis and down > across and down > 0:
        largest = down
        dic.update({pas: ((row-1,col),(row,col), 'down')})
        
    if across > mis and across > down and across> 0:
        largest = across
        dic.update({pas: ((row,col-1),(row,col), 'across')})

    #TO-DO need to fix this. the across overwrites the key of the down
    if down == across and across == down and down > mis:
        largest = down
        dic.update({pas: ((row-1,col),(row,col), 'down')})
        dic.update({pas: ((row,col-1),(row,col), 'across')})
        
       
    #TO-DO may need to add an if to account for a mis is = to the score of a down or across

    #check to see if the largest number is larger than 0 if it is less than zero, zero is applyed to the cell
    if largest > 0:
        arr[row,col] = arr[row,col] + largest
    if largest <= 0:
        arr[row,col] = arr[row,col] + 0
        dic.update({pas: ((row,col), 'Zero')})
    
    
    
  


#For loop to intteratate through each cell, x is itterating through each row
for x in arr:
    #The if skips the first row because we dont need to change anything in it 
    
    if row != 0 and row <= len(side_word):
        #y goes through each number in the row 
        #within this for loop we calculate the number for the cell from a row from left to right. after a row is competed it continues to the next row
        for y in x:
            #This if statement compres the letter of the top and side word and came only run if it is not in the first collum 
            #because we dont need to chage anything in the first collum
            if col != 0 and col <= len(top_word):

                #if the top and side letters match the match function is run
                if side_word[row-1] == top_word[col-1]:
                # send this to the match
                    match(row,col,pas)
                    pas += 1
                #if the 2 letters do not match the math function runs to calculate the mis-matchs and gap penaltys
                else:
                    math(row,col,pas)
                    pas += 1
                #send to the math for Gap and Mis
            
            col += 1
                
    col = 0
    row += 1
   
print(arr) 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 5. 1. 0.]
 [0. 0. 5. 1. 4. 0.]
 [0. 0. 1. 4. 6. 3.]
 [0. 0. 0. 0. 3. 5.]]


In [122]:
#dictionalry (From cell)(to cell)(action / arrow of the cell leading from ---> current cell)
for x in dic: 
    print(dic[x])



((1, 1), 'Zero')
((1, 2), 'Zero')
((1, 3), 'Zero')
((1, 4), 'Zero')
((1, 5), 'Zero')
((2, 1), 'Zero')
((2, 2), 'Zero')
((1, 2), (2, 3), 'diagnal')
((2, 3), (2, 4), 'across')
((2, 5), 'Zero')
((3, 1), 'Zero')
((2, 1), (3, 2), 'diagnal')
((3, 2), (3, 3), 'across')
((2, 3), (3, 4), 'diagnal')
((3, 5), 'Zero')
((4, 1), 'Zero')
((3, 2), (4, 2), 'down')
((3, 2), (4, 3), 'diagnal')
((3, 3), (4, 4), 'diagnal')
((3, 4), (4, 5), 'diagnal')
((5, 1), 'Zero')
((5, 2), 'Zero')
((5, 3), 'Zero')
((4, 3), (5, 4), 'diagnal')
((4, 4), (5, 5), 'diagnal')


In [123]:
#meathod used to find the largest number in the table
print('The largest number in the table is:' , arr.max())
#meathod used to find the index in the 2D array (table) of the largest number 
i, j = np.unravel_index(arr.argmax(), arr.shape)
print(i,j)



The largest number in the table is: 6.0
4 4


In [126]:
#Group of lists used for printing the allignments and the optimal score
gap_print = []
num_print = []
cell_print = []

lar = (i,j)
save = 0
#The values and keys that are sored in the dic dictinary is turned into a list to make it easy to work with
keys = list(dic.keys())
val = list(dic.values())
lar_found = False






#For loop used for the trace back of the table. starts searching in revers order of the values list for faster results
for y in reversed(val):
    
    temp = y
    #first if statement to find the largest if the first ellement in the cell entry is the same address as the largest number saved in lar 
    #the cell that leads to the larges number is saved in the save varible and the information for the val entry is saved to the alignment lists
    if temp[1] == lar and lar_found == False:
        save = temp[0]
        
        #adds the arrow direction to a list to be printed later
        gap_print.append(temp[2])
        num = arr[temp[1]]
        num_print.append(num)
        cell_print.append(temp[1])
        lar_found = True
        
    #second if statement will only trigger if the cell of the largest value has been found
    if temp[1] == save and lar_found == True:

        #these 2 if statements to trace back cells that do not have 0's in them. cells that contain 0 only have 2 values saved in the dictionary.
        #if the cell is not 0 than 
        if len(temp) != 2:
            save = temp[0]
            gap_print.append(temp[2])
            num = arr[temp[1]]
            num_print.append(num)
            cell_print.append(temp[1])
                
       
    #The values that are being traced back are deleted from the possible values that can be compared to. 
    #This saves memory and computing power from so that they are not compared to again
    if y in val: val.remove(y)
        
        
   

    

In [127]:
print(cell_print)
print(num_print)
print(gap_print)

[(4, 4), (3, 3), (3, 2)]
[6.0, 1.0, 5.0]
['diagnal', 'across', 'diagnal']


In [128]:
print('The optimal local alignment is:')
align_score = 0.0
p = 0
top_alignment = []
side_alignment = []

#The for loop goes through the cordinates savedin cell_print
for x in cell_print:
    #the corinites are saved to there respective varible
    col = x[1]
    row = x[0]
    
    #the following if statements are used to insert gaps and letters into the top and side word alignments
    #the alignment depends on the arrow values stored in the gap_print list
    #each if statement also adds the value stored in the cell that is saved in the num_print list for the total optimal alignment score
    #p is used as a constant itterating value for each of the 3 lists of information
    
    if gap_print[p] == 'diagnal':
        top_alignment.append(top_word[col-1])
        side_alignment.append(side_word[row-1])
    elif gap_print[p] == 'across':
        top_alignment.append(top_word[col-1])
        side_alignment.append('-')
    elif gap_print[p] == 'down':
        top_alignment.append('-')
        side_alignment.append(side_word[row-1])
    align_score = align_score + num_print[p]
    p += 1

#The 2 final alignments are reversed and printed aling with the optimal score
top_alignment.reverse()
side_alignment.reverse()
print(top_alignment)
print(side_alignment)
print('The total alignment score is:' , align_score)

The optimal local alignment is:
['a', 'l', 't']
['a', '-', 't']
The total alignment score is: 12.0
